//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("posTest.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string eposta {
            get {
                return ResourceManager.GetString("eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Ünvanı.
        /// </summary>
        public static string firmaunvani {
            get {
                return ResourceManager.GetString("firmaunvani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik Tarihi.
        /// </summary>
        public static string gecerliliktarihi {
            get {
                return ResourceManager.GetString("gecerliliktarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası.
        /// </summary>
        public static string gizlilikpolitikasi {
            get {
                return ResourceManager.GetString("gizlilikpolitikasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu.
        /// </summary>
        public static string guvenlikkodu {
            get {
                return ResourceManager.GetString("guvenlikkodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenli Ödeme Sayfasına Hoşgeldiniz.
        /// </summary>
        public static string hosgeldiniz {
            get {
                return ResourceManager.GetString("hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası.
        /// </summary>
        public static string kartnumarasi {
            get {
                return ResourceManager.GetString("kartnumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Sahibi.
        /// </summary>
        public static string kartsahibi {
            get {
                return ResourceManager.GetString("kartsahibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartı Bilgileri.
        /// </summary>
        public static string kredikartibilgileri {
            get {
                return ResourceManager.GetString("kredikartibilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Seçenekleri.
        /// </summary>
        public static string odemesecenekleri {
            get {
                return ResourceManager.GetString("odemesecenekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tutarı.
        /// </summary>
        public static string odemetutari {
            get {
                return ResourceManager.GetString("odemetutari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödemeyi Onayla.
        /// </summary>
        public static string odemeyionayla {
            get {
                return ResourceManager.GetString("odemeyionayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeyen Bilgileri.
        /// </summary>
        public static string odeyenbilgileri {
            get {
                return ResourceManager.GetString("odeyenbilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okudum kabul ettim.
        /// </summary>
        public static string okudumkabulettim {
            get {
                return ResourceManager.GetString("okudumkabulettim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Kullanım Yılı.
        /// </summary>
        public static string sonkullanimyili {
            get {
                return ResourceManager.GetString("sonkullanimyili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Seçenekleri.
        /// </summary>
        public static string taksitsecenekleri {
            get {
                return ResourceManager.GetString("taksitsecenekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek Çekim.
        /// </summary>
        public static string tekcekim {
            get {
                return ResourceManager.GetString("tekcekim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslimat ve İade.
        /// </summary>
        public static string teslimatveiade {
            get {
                return ResourceManager.GetString("teslimatveiade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi Yap.
        /// </summary>
        public static string uyegirisiyap {
            get {
                return ResourceManager.GetString("uyegirisiyap", resourceCulture);
            }
        }
    }
}
