//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aspnet_Users()
        {
            this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
            this.aspnet_PersonalizationPerUser1 = new HashSet<aspnet_PersonalizationPerUser>();
            this.aspnet_PersonalizationPerUser2 = new HashSet<aspnet_PersonalizationPerUser>();
            this.aspnet_PersonalizationPerUser3 = new HashSet<aspnet_PersonalizationPerUser>();
            this.aspnet_UsersInRoles = new HashSet<aspnet_UsersInRoles>();
            this.aspnet_UsersInRoles1 = new HashSet<aspnet_UsersInRoles>();
            this.aspnet_UsersInRoles2 = new HashSet<aspnet_UsersInRoles>();
            this.aspnet_UsersInRoles3 = new HashSet<aspnet_UsersInRoles>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual aspnet_Applications aspnet_Applications1 { get; set; }
        public virtual aspnet_Applications aspnet_Applications2 { get; set; }
        public virtual aspnet_Applications aspnet_Applications3 { get; set; }
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual aspnet_Membership aspnet_Membership1 { get; set; }
        public virtual aspnet_Membership aspnet_Membership2 { get; set; }
        public virtual aspnet_Membership aspnet_Membership3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser3 { get; set; }
        public virtual aspnet_Profile aspnet_Profile { get; set; }
        public virtual aspnet_Profile aspnet_Profile1 { get; set; }
        public virtual aspnet_Profile aspnet_Profile2 { get; set; }
        public virtual aspnet_Profile aspnet_Profile3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersInRoles> aspnet_UsersInRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersInRoles> aspnet_UsersInRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersInRoles> aspnet_UsersInRoles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_UsersInRoles> aspnet_UsersInRoles3 { get; set; }
    }
}
