//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bankalar()
        {
            this.BankaParametreleri = new HashSet<BankaParametreleri>();
            this.FirmaBankaBaglama = new HashSet<FirmaBankaBaglama>();
            this.FirmaTaksitleri = new HashSet<FirmaTaksitleri>();
        }
    
        public int Id { get; set; }
        public string BankaAdi { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankaParametreleri> BankaParametreleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaBankaBaglama> FirmaBankaBaglama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaTaksitleri> FirmaTaksitleri { get; set; }
    }
}
