//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaPosBilgileri
    {
        public int Id { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public string Banka { get; set; }
        public string MagazaNumarasi { get; set; }
        public string MagazaAnahtar { get; set; }
        public Nullable<bool> Gecerli { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
    }
}
