//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBankaBaglama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaBankaBaglama()
        {
            this.FirmaParametreleri = new HashSet<FirmaParametreleri>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<int> BankaId { get; set; }
        public Nullable<bool> Gecerli { get; set; }
    
        public virtual Bankalar Bankalar { get; set; }
        public virtual Firmalar Firmalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaParametreleri> FirmaParametreleri { get; set; }
    }
}
