//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmalar()
        {
            this.FirmaBankaBaglama = new HashSet<FirmaBankaBaglama>();
            this.FirmaPosBilgileri = new HashSet<FirmaPosBilgileri>();
            this.FirmaTaksitleri = new HashSet<FirmaTaksitleri>();
            this.OdemeIstekleri = new HashSet<OdemeIstekleri>();
            this.Odemeler = new HashSet<Odemeler>();
            this.Uyeler = new HashSet<Uyeler>();
        }
    
        public int Id { get; set; }
        public string FirmaAdi { get; set; }
        public string Yetkili { get; set; }
        public string Domain { get; set; }
        public string Logo { get; set; }
        public string FirmaRenk { get; set; }
        public string Adres { get; set; }
        public string EPosta { get; set; }
        public string Telefon { get; set; }
        public string SiteAdres { get; set; }
        public Nullable<bool> UyeliksizOdeme { get; set; }
        public Nullable<bool> UyelikOdeme { get; set; }
        public Nullable<bool> DovizOdeme { get; set; }
        public string EmailSunucu { get; set; }
        public string EmailSunucuPort { get; set; }
        public string EmailKullaniciAdi { get; set; }
        public string EmailParola { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<bool> demoOnay { get; set; }
        public Nullable<System.DateTime> olusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaBankaBaglama> FirmaBankaBaglama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaPosBilgileri> FirmaPosBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaTaksitleri> FirmaTaksitleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdemeIstekleri> OdemeIstekleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odemeler> Odemeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uyeler> Uyeler { get; set; }
    }
}
