//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartBinNumaralari
    {
        public int Id { get; set; }
        public Nullable<int> bankaKodu { get; set; }
        public string bankaAdi { get; set; }
        public string typ { get; set; }
        public string subType { get; set; }
        public string @virtual { get; set; }
        public string prepaid { get; set; }
    }
}
