//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int Id { get; set; }
        public string EPosta { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Ip { get; set; }
        public string Cihaz { get; set; }
        public Nullable<int> FirmaId { get; set; }
    }
}
