//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<bool> Bayi { get; set; }
        public Nullable<bool> Satici { get; set; }
        public string EPosta { get; set; }
        public string Sifre { get; set; }
        public string TelNo { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<int> BayiId { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
    }
}
